services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=bitespeed
      - POSTGRES_PASSWORD=bitespeed
      - POSTGRES_DB=bitespeed
    ports:
      - "5432:5432"
    restart: always

  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=8080
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=bitespeed
      - POSTGRES_PASSWORD=bitespeed
      - POSTGRES_DB=bitespeed
    ports:
      - "8080:8080"
    restart: always
